//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 02:04:02 PM GFT 
//


package com.nosbielc.crawler.banco.soap.service;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transacao" type="{http://com.nosbielc.crawler/banco/soap-web-service}transacao"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transacao"
})
@XmlRootElement(name = "getAllTransacoesResponse")
public class GetAllTransacoesResponse {

    @XmlElement(required = true)
    protected List<Transacao> transacao;

    /**
     * Gets the value of the transacao property.
     * 
     * @return
     *     possible object is
     *     {@link Transacao }
     *     
     */
    public List<Transacao> getTransacao() {
        return transacao;
    }

    /**
     * Sets the value of the transacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link Transacao }
     *     
     */
    public void setTransacao(List<Transacao> value) {
        this.transacao = value;
    }

}
