//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 02:04:02 PM GFT 
//


package com.nosbielc.crawler.banco.soap.service;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.spring.guides.gs_producing_web_service package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.spring.guides.gs_producing_web_service
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAllTransacoesResponse }
     * 
     */
    public GetAllTransacoesResponse createGetAllTransacoesResponse() {
        return new GetAllTransacoesResponse();
    }

    /**
     * Create an instance of {@link Transacao }
     * 
     */
    public Transacao createTransacao() {
        return new Transacao();
    }

    /**
     * Create an instance of {@link GetTransacaoResponse }
     * 
     */
    public GetTransacaoResponse createGetTransacaoResponse() {
        return new GetTransacaoResponse();
    }

    /**
     * Create an instance of {@link GetTransacaoRequest }
     * 
     */
    public GetTransacaoRequest createGetTransacaoRequest() {
        return new GetTransacaoRequest();
    }

    /**
     * Create an instance of {@link GetAllTransacoesRequest }
     * 
     */
    public GetAllTransacoesRequest createGetAllTransacoesRequest() {
        return new GetAllTransacoesRequest();
    }

}
