//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.12 at 02:04:02 PM GFT 
//


package com.nosbielc.crawler.banco.soap.service;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transacao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transacao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="descricao" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ativo" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tipoTransacao" type="{http://com.nosbielc.crawler/banco/soap-web-service}tipoTransacao"/>
 *         &lt;element name="valorTransacao" type="{http://com.nosbielc.crawler/banco/soap-web-service}decimalValue"/>
 *         &lt;element name="dateTimeTransferencia" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="conta" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transacao", propOrder = {
    "id",
    "descricao",
    "ativo",
    "tipoTransacao",
    "valorTransacao",
    "dateTimeTransferencia",
    "conta"
})
public class Transacao {

    protected long id;
    @XmlElement(required = true)
    protected String descricao;
    protected int ativo;
    protected int tipoTransacao;
    @XmlElement(required = true)
    protected BigDecimal valorTransacao;
    @XmlElement(required = true)
    protected String dateTimeTransferencia;
    @XmlElement(required = true)
    protected String conta;

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the descricao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescricao() {
        return descricao;
    }

    /**
     * Sets the value of the descricao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescricao(String value) {
        this.descricao = value;
    }

    /**
     * Gets the value of the ativo property.
     * 
     */
    public int getAtivo() {
        return ativo;
    }

    /**
     * Sets the value of the ativo property.
     * 
     */
    public void setAtivo(int value) {
        this.ativo = value;
    }

    /**
     * Gets the value of the tipoTransacao property.
     * 
     */
    public int getTipoTransacao() {
        return tipoTransacao;
    }

    /**
     * Sets the value of the tipoTransacao property.
     * 
     */
    public void setTipoTransacao(int value) {
        this.tipoTransacao = value;
    }

    /**
     * Gets the value of the valorTransacao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTransacao() {
        return valorTransacao;
    }

    /**
     * Sets the value of the valorTransacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTransacao(BigDecimal value) {
        this.valorTransacao = value;
    }

    /**
     * Gets the value of the dateTimeTransferencia property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateTimeTransferencia() {
        return dateTimeTransferencia;
    }

    /**
     * Sets the value of the dateTimeTransferencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateTimeTransferencia(String value) {
        this.dateTimeTransferencia = value;
    }

    /**
     * Gets the value of the conta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConta() {
        return conta;
    }

    /**
     * Sets the value of the conta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConta(String value) {
        this.conta = value;
    }

}
